version: "3"

volumes:
    mariadb:

services:

  mariadb:
      image: mariadb:10.3
      container_name: wpsec-mariadb
      ports:
        - 3306:3306
      environment:
          MYSQL_ROOT_PASSWORD: wpsec
          MYSQL_USER: wpsec
          MYSQL_PASSWORD: wpsec
          MYSQL_DATABASE: wpsec
      volumes:
          - mariadb:/var/lib/mysql

  php-cli:
     container_name: wpsec-phpcli
     build: docker/images/php-cli
     volumes:
        - './:/home/wp:rw'
        - './docker/images/php-cli/resources/php.ini:/usr/local/etc/php/php.ini:ro'
     links:
        - mariadb